// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0oLmclkGaax3bVw3He7T091A0uP0qZuE',
    appId: '1:686322123729:web:994c9e312af46206de96f0',
    messagingSenderId: '686322123729',
    projectId: 'wiqaya-e1b01',
    authDomain: 'wiqaya-e1b01.firebaseapp.com',
    storageBucket: 'wiqaya-e1b01.firebasestorage.app',
    measurementId: 'G-M8LWHGVFFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuj5v_PUPdGUnC9WKpKo-mGyJLLni63yY',
    appId: '1:686322123729:android:bfe9b200da3c93b1de96f0',
    messagingSenderId: '686322123729',
    projectId: 'wiqaya-e1b01',
    storageBucket: 'wiqaya-e1b01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhP7hsG8tFvc7c0W38HcH8n_94EHqANn0',
    appId: '1:686322123729:ios:659866de2dbaf02bde96f0',
    messagingSenderId: '686322123729',
    projectId: 'wiqaya-e1b01',
    storageBucket: 'wiqaya-e1b01.firebasestorage.app',
    iosBundleId: 'com.example.wiqayaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhP7hsG8tFvc7c0W38HcH8n_94EHqANn0',
    appId: '1:686322123729:ios:659866de2dbaf02bde96f0',
    messagingSenderId: '686322123729',
    projectId: 'wiqaya-e1b01',
    storageBucket: 'wiqaya-e1b01.firebasestorage.app',
    iosBundleId: 'com.example.wiqayaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0oLmclkGaax3bVw3He7T091A0uP0qZuE',
    appId: '1:686322123729:web:71141791341ffe1bde96f0',
    messagingSenderId: '686322123729',
    projectId: 'wiqaya-e1b01',
    authDomain: 'wiqaya-e1b01.firebaseapp.com',
    storageBucket: 'wiqaya-e1b01.firebasestorage.app',
    measurementId: 'G-DFK8K4E8MF',
  );

}